const data = [
    {
      id: 1,
      type: "House",
      price: 200000,
      seller: "John Doe",
    sellerEmail: "michael@example.com",
      phone1:"+756765543456",      time: "2 days ago",
      surface: "150m²",
      address: "123 Main St",
      city: "New York",
      etages: 2,
      baths: 2,
      image: "./img1.jpg",
      images: ["./img10.jpg", "./img1.jpg", "./img2.jpg", "./img3.jpg", "./img4.jpg"],
      rate: "Passable",
      description: "A cozy house located in a quiet neighborhood with easy access to amenities.",
      for : "mounthly",
starsNumber: 1
    },
    {
      id: 2,
      type: "House",
      price: 250000,
      seller: "Alice Smith",
      sellerEmail: "alice@example.com",
      phone1:"+7652434456",
      time: "1 day ago",
      surface: "200m²",
      address: "456 Elm St",
      city: "Los Angeles",
      etages: 1,
      baths: 3,
      image: "./img2.jpg",
      images: ["./img10.jpg", "./img1.jpg", "./img2.jpg", "./img3.jpg", "./img4.jpg"],
      rate: "Bien",
      description: "Spacious family home with a beautiful garden and close proximity to schools.",
      for : "mounthly",
starsNumber: 4
    },
    {
      id: 3,
      type: "House",
      price: 300000,
      seller: "Michael Johnson",
    sellerEmail: "john@example.com",
      phone1:"+12357563356",
      time: "3 days ago",
      surface: "300m²",
      address: "Marrakech avenue ABC",
      city: "Marrakech",
      etages: 3,
      baths: 4,
      image: "./img3.jpg",
      images: ["./img10.jpg", "./img1.jpg", "./img2.jpg", "./img3.jpg", "./img4.jpg"],
      rate: "Très bien",
      description: "Luxurious villa with stunning views of the surrounding countryside.",
      for : "mounthly",
starsNumber: 5
    },
    {
      id: 4,
      type: "House",
      price: 180000,
      seller: "Emily Brown",
    sellerEmail: "michael@example.com",
      phone1:"+9832983298",      time: "4 days ago",
      surface: "120m²",
      address: "789 Oak St",
      city: "London",
      etages: 2,
      baths: 1,
      image: "./img4.jpg",
      images: ["./img10.jpg", "./img1.jpg", "./img2.jpg", "./img3.jpg", "./img4.jpg"],
      rate: "Passable",
      description: "Charming cottage with a quaint garden, perfect for a small family.",
      for : "sale",
starsNumber: 1
    },
    {
      id: 5,
      type: "villa",
      price: 320000,
      seller: "Daniel Wilson",
    sellerEmail: "alice@example.com",
      phone1:"+75843759345",      time: "5 days ago",
      surface: "250m²",
      address: "1011 Pine St",
      city: "Paris",
      etages: 2,
      baths: 2,
      image: "./img5.jpg",
      images: ["./img10.jpg", "./img1.jpg", "./img2.jpg", "./img3.jpg", "./img4.jpg"],
      rate: "Bien",
      description: "Modern home with sleek design features and ample space for entertaining.",
      for : "mounthly",
starsNumber: 4
    },
    {
      id: 6,
      type: "villa",
      price: 280000,
      seller: "Sophia Taylor",
    sellerEmail: "michael@example.com",
      phone1:"+6346346346",      time: "6 days ago",
      surface: "180m²",
      address: "1313 Maple St",
      city: "Berlin",
      etages: 1,
      baths: 2,
      image: "./img6.jpg",
      images: ["./img10.jpg", "./img1.jpg", "./img2.jpg", "./img3.jpg", "./img4.jpg"],
      rate: "Passable",
      description: "Classic-style house with elegant interior finishes and a spacious backyard.",
      for : "sale",
starsNumber: 5
    },
    {
      id: 7,
      type: "appartement",
      price: 350000,
      seller: "Matthew Martinez",
    sellerEmail: "john@example.com",
      phone1:"+6346346346565",
      time: "1 week ago",
      surface: "220m²",
      address: "1415 Cedar St",
      city: "Tokyo",
      etages: 3,
      baths: 3,
      image: "./img7.jpg",
      images: ["./img10.jpg", "./img1.jpg", "./img2.jpg", "./img3.jpg", "./img4.jpg"],
      rate: "Bien",
      description: "Well-maintained property with multiple bedrooms and a lovely outdoor patio.",
      for : "sale",
starsNumber: 3
    },
    {
      id: 8,
      type: "appartement",
      price: 400000,
      seller: "Olivia Brown",
    sellerEmail: "john@example.com",
      phone1:"+212534534µ",
      time: "2 weeks ago",
      surface: "270m²",
      address: "1617 Oak St",
      city: "Sydney",
      etages: 4,
      baths: 4,
      image: "./img8.jpg",
      images: ["./img10.jpg", "./img1.jpg", "./img2.jpg", "./img3.jpg", "./img4.jpg"],
      rate: "Très bien",
      description: "Elegant mansion featuring high-end finishes and breathtaking views of the city.",
      for : "mounthly",
starsNumber: 2
    },
    {
      id: 9,
      type: "WG",
      price: 220000,
      seller: "James Johnson",
    sellerEmail: "michael@example.com",
      phone1:"+7567576666",      time: "3 weeks ago",
      surface: "160m²",
      address: "1819 Maple St",
      city: "Toronto",
      etages: 2,
      baths: 2,
      image: "./img9.jpg",
      images: ["./img10.jpg", "./img1.jpg", "./img2.jpg", "./img3.jpg", "./img4.jpg"],
      rate: "Passable",
      description: "Quaint home with rustic charm and a peaceful ambiance, perfect for relaxation.",
      for : "sale",
starsNumber: 5
    },
    {
      id: 10,
      type: "WG",
      price: 300000,
      seller: "Charlotte Wilson",
    sellerEmail: "alice@example.com",
      phone1:"+9879942334",      time: "4 weeks ago",
      surface: "190m²",
      address: "2021 Pine St",
      city: "Miami",
      etages: 2,
      baths: 3,
      image: "./img10.jpg",
      images: ["./img10.jpg", "./img1.jpg", "./img2.jpg", "./img3.jpg", "./img4.jpg"],
      rate: "Bien",
      description: "Contemporary-style house featuring open-plan living spaces and lots of natural light.",
      for : "sale",
starsNumber: 3
    },
  ];
  
  export default data;
  